# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

use strict;

$num = 1;
$num2 = 2;
$temp;
$res = 0;

while(1){
	if($num2 < 4000000){
		print("$num2\n");
		if($num2 % 2 == 0){
			$res += $num2;
		}
	}else{
		last;
	}
	$temp = $num2;
	$num2 = $num+$num2;
	$num = $temp;
}

print("$res\n");
